### ISSUE TITLE
$sails.get not called on page reload

### ISSUE THREAD

**Issue by ArtworkAD** [janpantel/angular-sails#21]
$sails.get("/model").success(function(data) {
        console.log(data);
    }).error(function(error){
        console.log('error');
    });

E.g. when I put this code on the landing page, nothing happens. I navigate forward and back again, I see the data in log. However initially the get does not seem to get called.

**Comment by mukk85** [comment]
Any word on fixing this? Adding the code into the connect event works for refresh but not when navigating the site.

**Comment by TheSharpieOne** [comment]
This should be resolved now with the new version of [sails.io.js](https://github.com/balderdashy/sails.io.js).  It will handle queuing requests if the socket is not connected/ready.
