### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by ghost** [janpantel/angular-sails#35]
Is a file uploads feature in the roadmap?

**Comment by TheSharpieOne** [comment]
Note: Angular currently (as of 1.4) does not support the file input
> Note: Not every feature offered is available for all input types. Specifically, data binding and event handling via ng-model is unsupported for input[file].

If angular would support input[file] and 'normalize' the file's data, I would look into adding the ability for angular-sails to send a file.  But as of now, the [file API](https://developer.mozilla.org/en-US/docs/Web/API/File) that browsers have is only a [working draft](http://dev.w3.org/2006/webapi/FileAPI/) and is not implemented in all of the browser that angular tries to support.
