### ISSUE TITLE
angular.js:10126 TypeError: Cannot read property 'once' of undefined

### ISSUE THREAD

**Issue by misterch0c** [janpantel/angular-sails#53]
I just made a new project using slush. Then bower install angular-sails --save
Used your example code and error. See the gist for code and error
https://gist.github.com/misterch0c/b30aec433062cdb0c44b

**Comment by TheSharpieOne** [comment]
What version of sails.io.js are you using?

But what is happening is sails.io.js doesn't have a `.once()` method so angular-sails tries to grab it from the "raw" socket that is exposed through sail.io.js, but it appears that the "raw" socket is not there.

**Comment by misterch0c** [comment]
```// socket.io-1.2.1
// (from http://socket.io/download/)```
Got it from the bower install and it seems to have the `.once()` method

**Comment by TheSharpieOne** [comment]
[sails.io.js](https://github.com/balderdashy/sails.io.js) is a dependency of angular-sails and must be included.  We removed this dependency in the next version which should be released within the next month or so

**Comment by misterch0c** [comment]
Sorry that header was from the header of another sails.io.js ..
```  "name": "sails.io.js",
  "main": "dist/sails.io.js",
  "version": "0.11.4"```
So I ran bower update sails.io.js to get 0.11.5 but I'm still facing the same error

**Comment by TheSharpieOne** [comment]
Because `.once()` is different from `on` and `off` (its not exposed directly), it is a special case and we should expose it differently.

**Comment by TheSharpieOne** [comment]
Ok, there is a new build that has been released that should solve your issue..  The new release is 1.1.1 and you should be able to get it via bower.

**Comment by misterch0c** [comment]
Works like a charm now, thank you
