### ISSUE TITLE
sockets don't connect on android browser

### ISSUE THREAD

**Issue by mackenrou** [janpantel/angular-sails#65]
Hi,
I updated to sails@0.11.0 / angular-sails@1.1.3 and now sockets don't connect on android browser.

I think that is not necessary to set transports in config (line 65) because it works when i remove that line (or set polling at first).
However, when i change this and test in a tablet with android 4.2.2 is connected but requests can't reach server (only in that device, in others is fine).

This problem did not exist with sails@0.10.5 / angular-sails@1.0.5.

Any ideas?

**Comment by TheSharpieOne** [comment]
Are you still experiencing this issue?  Can you debug the tablet via [Remote Debugging on Android with Chrome](https://developer.chrome.com/devtools/docs/remote-debugging)?  If so, can you see any errors in the console and/or network related issues (is it trying to switch to fallback methods such as long-polling?)

**Comment by TheSharpieOne** [comment]
Closing: Inactive.
