### ISSUE TITLE
post() is successful, but the callback isn't called

### ISSUE THREAD

**Issue by LukasKnuth** [janpantel/angular-sails#66]
Here is the relevant part of my Angular code:

```
$scope.addTodo = function(){
	$sails.post("/todos", {what: $scope.new_todo.what}, function(resp){
		$scope.todos.push(resp);
	});
	$scope.new_todo = {};
}
```

The request is successful and if I listen for any events on the `todos`-model, they get send. But the callback-function is never called.

I tried the same with the normal `io.socket.post()` function, and then the callback function is called fine:

```
socket.post("/todos", {what:"test"}, function(data){
	console.log(data);
});
```

The `todos`-model is managed via blueprint. Am I missing something?

**Comment by TheSharpieOne** [comment]
It returns a promise. I'm mobile right now so I cannot post an example, but there are some examples in the README.

**Comment by LukasKnuth** [comment]
Indeed it does, thanks!

Although it's kinda confusing that the API documentation states that the `$sails`-object works exactly like the `io.sails`-object.

**Comment by TheSharpieOne** [comment]
Yeah, it used to be callback based, and that documentation may be old.  It changed to be more 'angular' and use promises (and at one point did both callback and return a promise, but somewhere callbacks were removed).
