### ISSUE TITLE
Changing default host / port (2.0.0 beta 2)

### ISSUE THREAD

**Issue by AdamJessop** [janpantel/angular-sails#70]
Hi, 

I have been working with angular-sails for a while however I wanted to update to the latest beta to get access to the defaults for help with authorisation however it has since broken my ability to change the default URL for the socket service.

Previously I was doing $sailsProvider.url = 'http://host:port' however it appears this has no effect.

Is there an updated method for achieving the same result?

Cheers,
Adam.

**Comment by AdamJessop** [comment]
Closing this, figured it out.

app.config($sailsProvider) {
   $sailsProvider.config.url = 'http://host:port';
}

**Comment by TheSharpieOne** [comment]
That change was unintentional and looking at the code is a bug.

**Comment by TheSharpieOne** [comment]
This should be fixed in 2.0.0 beta 3 which has been released.

**Comment by hugotown** [comment]
Configuring default host / port
how can i load the backendUrl , reading a config.json through $http request ? , is it possible ?

or change it dynamically?

regards
