### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by AlexDel** [janpantel/angular-sails#75]
Hello guys!

I know that IE is going to deprecated by Microsoft, but does your lib supports this? I have some stuff performed by ngSails that works in all modern browsers but for IE11.

Thanks in advance!

**Comment by TheSharpieOne** [comment]
We try to support all browsers that are officially supported by the latest
stable release of angular.  Is there anything particular that is not
working in IE11?  Do you see any errors in it's console? Is it easily
reproducible? Can you post a script with the minimum needed to reproduce
the error?

**Comment by TheSharpieOne** [comment]
Closing: Inactive.
