### ISSUE TITLE
Is angular-sails compatible with socket.io v.1?

### ISSUE THREAD

**Issue by metalaureate** [janpantel/angular-sails#91]
Sorry if this is a dumb question, but is this library compatible with socket.io v.1.x? Sails v 0.11 upgraded to socket.io v.1. Thaks for any clarification!

**Comment by TheSharpieOne** [comment]
v2 utilizes socket.io[-client] 1.3.0 and above.
v1 doesn't depend on socket.io, it depends on sails.io.js, which in-turn depends on socket.io.. so it would be up to them to provide support for v.1.x (which I believe they do).

If this answers your question, please close the issue.

**Comment by metalaureate** [comment]
Thank you for the clarification.
